# Generated by Django 5.2.7 on 2025-11-28 12:09

import django.db.models.deletion
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_name', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=6)),
                ('zip_code', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('uf', localflavor.br.models.BRStateField(max_length=2, verbose_name='UF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_adress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
