# Generated by Django 5.2.7 on 2026-01-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_shipping_city_order_shipping_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_quartier',
            field=models.CharField(default='N/D', max_length=29),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=29),
        ),
    ]
